language: android

jdk:
  - oraclejdk8

before_script:
 - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before-script:
  - "android update sdk --no-ui --filter build-tools-24.0.2,android-24,extra-android-m2repository"
script:
  - ./gradlew clean assemble

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

notifications:
  email:
    recipients:
      - lortoso@gmail.com
      - Hanau.emile@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19